# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://siggaard.io"

# The name of this wonderful theme ;-).
theme = 'typo'

# Basic metadata configuration for your blog.
title = "siggaard.io"
author = "Simon Siggaard"
copyright = "Copyright © 2024, Simon Siggaard."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = "Welcome!"
homeIntroContent = """
I write truisms about leadership and parenting.
"""

# Collection to display on home
homeCollectionTitle = 'Blog'
homeCollection = 'blog'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/simonsiggaard/"

[[params.social]]
name = "github"
url = "https://github.com/simon-siggaard"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blog"
url = "/blog"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
